name: Construção e Testes

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        pip install pytest  # Instale o pytest antes de executar os testes

    - name: Teste01
      run: |
        pytest Teste1.py  # Especifique o arquivo que contém os testes
        
    - name: Teste02
      run: |
        pytest Teste2.py

    - name: Teste03
      run: |
        pytest Teste3.py

    - name: Teste04
      run: |
        pytest Teste4.py
        
    - name: Teste05
      run: |
        pytest Teste5.py
