name: Construção e Testes

on:
  pull_request:
    branches: [main]

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other repository
        uses: actions/checkout@v2
        with:
          repository: FeDextroyer/TesteFinal
          ref: main
          path: TesteFinal
      - name: Teste2
        run: |
          pytest Teste1.py
        
      - name: Teste2
        run: |
          pytest Teste2.py
  
      - name: Teste3
        run: |
          pytest Teste3.py
  
      - name: Teste4
        run: |
          pytest Teste4.py
  
      - name: Teste5
        run: |
          pytest Teste5.py
